[package]
name = "orb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytes = "1"
bytesize = { version = "1", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
ctrlc = { version = "3", features = ["termination"] }
env_logger = "0.11"
futures-util = "0.3"
itertools = "0.12.1"
log = "0.4.21"
orb-ublk = { path = "./orb-ublk" }
parking_lot = "0.12"
rustix = "0.38"
sd-notify = "0.4.1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "sync", "time"] }
toml = "0.8"

[dev-dependencies]
rustix = { version = "0.38", features = ["fs"] }

[workspace]
resolver = "2"
members = ["orb-ublk"]
