[package]
name = "orb"
version = "0.1.0"
edition = "2021"

[features]
default = []
completion = ["dep:clap", "dep:clap_complete"]

[dependencies]
anyhow = "1"
bytes = "1"
bytesize = { version = "1", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.11"
futures-util = { version = "0.3", features = ["io"] }
humantime = "2"
itertools = "0.12.1"
log = "0.4.21"
lru = "0.12.3"
onedrive-api = { git = "https://github.com/oxalica/onedrive-api.git", rev = "c6b76ed493b2e226c4cf09871c62c8955ee50520" }
orb-ublk = { path = "./orb-ublk" }
parking_lot = "0.12"
reqwest = { version = "0.12", features = ["stream"] }
rustix = { version = "0.38", features = ["time"] }
sd-notify = "0.4.1"
serde = { version = "1", features = ["derive"] }
serde-inline-default = "0.2"
serde_json = "1.0.114"
tokio = { version = "1", features = ["macros", "signal", "sync", "time"] }
toml = "0.8"

[dev-dependencies]
rustix = { version = "0.38", features = ["fs"] }

[build-dependencies]
clap = { version = "4", optional = true, features = ["derive"] }
clap_complete = { version = "4", optional = true }

[workspace]
resolver = "2"
members = ["orb-ublk"]

[profile.bench]
debug = "full"
