[package]
name = "orb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytes = "1"
bytesize = { version = "1", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
ctrlc = { version = "3", features = ["termination"] }
dirs = "5.0.1"
env_logger = "0.11"
futures-util = { version = "0.3", features = ["io"] }
itertools = "0.12.1"
log = "0.4.21"
lru = "0.12.3"
onedrive-api = { git = "https://github.com/oxalica/onedrive-api.git", rev = "2872e5338d09a348be6f371ff073666dcc251405" }
orb-ublk = { path = "./orb-ublk" }
parking_lot = "0.12"
reqwest = { version = "0.11.26", features = ["stream"] }
rustix = "0.38"
sd-notify = "0.4.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1", features = ["macros", "sync", "time"] }
toml = "0.8"

[dev-dependencies]
rustix = { version = "0.38", features = ["fs"] }

[workspace]
resolver = "2"
members = ["orb-ublk"]

[profile.bench]
debug = "full"
