[package]
name = "orb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.2"
ctrlc = "3.4.2"
env_logger = "0.11"
io-uring = { version = "0.6.2", features = ["io_safety"] }
log = "0.4.20"
rustix = { version = "0.38.30", features = ["event", "mm", "process"] }
scopeguard = "1.2.0"
tokio = { version = "1.35.1", features = ["net", "rt"] }

[build-dependencies]
bindgen = "0.69.2"

[dev-dependencies]
anyhow = "1"
bytesize = "1.3.0"
clap = { version = "4.4.18", features = ["derive"] }
rand = "0.8.5"
rstest = "0.18.2"
rustix = { version = "0.38.30", features = ["fs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.35.1", features = ["time"] }
xshell = "0.2.5"
