name: CI
on:
  pull_request:
  push:

permissions:
  contents: read

env:
  RUST_BACKTRACE: full
  RUSTDOCFLAGS: -Dwarnings
  RUSTFLAGS: -Dwarnings

jobs:
  style:
    name: Code style
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        run: |
          rustup update --no-self-update stable
          rustup default stable

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Rustfmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D clippy::dbg_macro -D clippy::todo

      - name: Rustdoc
        run: cargo doc --workspace

  test:
    strategy:
      matrix:
        rust: [stable, '1.82'] # NB. Sync with Cargo.toml.
    name: Test ${{ matrix.rust }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Load kernel module ublk_drv
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes "linux-modules-extra-$(uname -r)"
          sudo modprobe ublk_drv

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust ${{ matrix.rust }}
        run: |
          rustup update --no-self-update ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --workspace --all-targets

      - name: Test
        run: cargo test --workspace --all-targets -- --include-ignored --test-threads=1
        env:
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: sudo

  nix-flake:
    name: Flake package
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Flake check
        run: nix flake check --no-update-lock-file --show-trace

      - name: Flake build
        run: nix build --no-update-lock-file --show-trace --print-build-logs
